app/src/Model/User/Entity/User/Email.php
<?php
declare(strict_types=1);

namespace App\Model\User\Entity\User;

use Webmozart\Assert\Assert;
class Email
{

    private  $value;

    public function __construct(string $value)
    {
        Assert::notEmpty($value);
        if (!filter_var($value, FILTER_VALIDATE_EMAIL)) {
            throw new \InvalidArgumentException('Incorrect email.');
        }
        $this->setValue(mb_strtolower($value));
    }

    public function setValue($value)
    {
        $this->value=$value;
    }

    public function getValue():string
    {
        return $this->value;
    }

    public function isEqual(self $other): bool
    {
        return $this->getValue() === $other->getValue();
    }

    public function __toString(): string
    {
        return $this->getValue();
    }
}

app/src/Model/User/Entity/User/EmailType.php
<?php
declare(strict_types=1);

namespace App\Model\User\Entity\User;

use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Types\StringType;

class EmailType extends StringType
{
    public const NAME='user_email';

    public function convertToDatabaseValue($value, AbstractPlatform $platform)
    {
        return $value instanceof Email ? $value->getValue() :$value;
    }

    public function convertToPHPValue($value, AbstractPlatform $platform)
    {
        return !empty($value)? new Email($value) : null;
    }

    public function getName():string
    {
        return self::NAME;
    }
}

app/src/Model/User/Entity/User/Id.php
<?php
declare(strict_types=1);

namespace App\Model\User\Entity\User;

use Ramsey\Uuid\Uuid;
use Webmozart\Assert\Assert;

class Id
{
    private $value;

    public function __construct(string $value)
    {
        Assert::notEmpty($value);
        $this->setValue($value);
    }

    public static function next(): self
    {
        return new self(Uuid::uuid4()->toString());
    }

    public function getValue(): string
    {
        return $this->value;
    }

    public function setValue(string $hash):void
    {
        $this->value=$hash;
    }

    public function __toString(): string
    {
        return $this->getValue();
    }

}

app/src/Model/User/Entity/User/IdType.php
<?php


namespace App\Model\User\Entity\User;

use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Types\GuidType;

class IdType extends GuidType
{
    public const NAME='user_id';

    public function convertToDatabaseValue($value, AbstractPlatform $platform)
    {
        return $value instanceof Id ? $value->getValue(): $value;
    }

    public function convertToPHPValue($value, AbstractPlatform $platform)
    {
        return !empty($value)? new Id($value):null;
    }

    public function getName()
    {
        return self::NAME;
    }
}

app/src/Model/User/Entity/User/Name.php
<?php
declare(strict_types=1);

namespace App\Model\User\Entity\User;

use Doctrine\ORM\Mapping as ORM;
use Webmozart\Assert\Assert;

/**
 * @ORM\Embeddable
 */
class Name
{
    /**
     * @var string
     * @ORM\Column (type="string")
     */
    private string $first;
    /**
     * @var string
     * @ORM\Column (type="string")
     */
    private string $last;

    public function __construct(string $first, string $last)
    {
        Assert::notEmpty($first);
        Assert::notEmpty($last);

        $this->setFirst($first);
        $this->setLast($last);
    }

    public function getFirst():string
    {
        return $this->first;
    }

    public function setFirst(string $first)
    {
        $this->first=$first;
    }

    public function getLast():string
    {
        return $this->last;
    }

    public function setLast(string $last)
    {
        $this->last=$last;
    }

    public function getFull(): string
    {
        return $this->first . ' ' . $this->last;
    }
}

app/src/Model/User/Entity/User/Network.php
<?php
declare(strict_types=1);

namespace App\Model\User\Entity\User;

use Ramsey\Uuid\Uuid;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="user_networks",
 *      uniqueConstraints={
 *      @ORM\UniqueConstraint(columns={"network", "identity"})
 *    })
 */
class Network
{
    /**
     * @var string
     * @ORM\Column(type="guid")
     * @ORM\Id
     */
    private $id;
    /**
     * @var User
     * @ORM\ManyToOne(targetEntity="User", inversedBy="networks")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id", nullable=false, onDelete="CASCADE")
     */
    private $user;

    /**
     * @var string
     * @ORM\Column(type="string", length=32, nullable=true)
     */
    private $network;

    /**
     * @var string
     * @ORM\Column(type="string", length=32, nullable=true)
     */
    private $identity;

    public function __construct(User $user, string $network, string $identity)
    {
        $this->id=Uuid::uuid4()->toString();
        $this->setUser($user);
        $this->setNetwork($network);
        $this->setIdentity($identity);
    }

    public function isForNetwork(string $network): bool
    {
        return $this->network === $network;
    }

    public function getUser():User
    {
        return $this->user;
    }

    public function setUser(User $user):void
    {
        $this->user=$user;
    }

    public function getNetwork(): string
    {
        return $this->network;
    }

    public function setNetwork(string $network):void
    {
        $this->network=$network;
    }

    public function getIdentity(): string
    {
        return $this->identity;
    }

    public function setIdentity(string $identity)
    {
        $this->identity=$identity;
    }

    public function isFor(string $network, string $identity): bool
    {
        return $this->network === $network && $this->identity === $identity;
    }
}

app/src/Model/User/Entity/User/ResetToken.php
<?php
declare(strict_types=1);

namespace App\Model\User\Entity\User;

use Webmozart\Assert\Assert;
use Doctrine\ORM\Mapping as ORM;

/**
 * Class ResetToken
 * @package App\Model\User\Entity\User
 * @ORM\Embeddable
 */
class ResetToken
{

    /**
     * @var string
     * @ORM\Column (type="string",nullable=true)
     */
    private $token;

    /**
     * @var \DateTimeImmutable
     * @ORM\Column (type="date_immutable", nullable=true)
     */
    private $expires;

    public function __construct(string $token, \DateTimeImmutable $expires)
    {
        $this->token = $token;
        $this->expires = $expires;
    }

    public function getToken():string
    {
        return $this->token;
    }

    public function setToken(string $token)
    {
        $this->token=$token;
    }

    public function getExpires():\DateTimeImmutable
    {
        return $this->expires;
    }

    public function setExpires(\DateTimeImmutable $expires)
    {
        $this->expires=$expires;
    }

    public function isExpiredTo(\DateTimeImmutable $date): bool
    {
        return $this->expires <= $date;
    }

    /**
     * @internal for postLoad callback
     * @return bool
     */
    public function isEmpty(): bool
    {
        return empty($this->token);
    }
}

app/src/Model/User/Entity/User/Role.php
<?php
declare(strict_types=1);

namespace App\Model\User\Entity\User;

use Webmozart\Assert\Assert;
class Role
{
    public const USER='ROLE_USER';
    public const ADMIN='ROLE_ADMIN';

    private $name;

    public function __construct(string $name)
    {
        Assert::oneOf($name,[
            self::USER,
            self::ADMIN
        ]);
        $this->setName($name);
    }

    public static function user(): self
    {
        return new self(self::USER);
    }

    public static function admin(): self
    {
        return new self(self::ADMIN);
    }

    public function isUser(): bool
    {
        return $this->name === self::USER;
    }

    public function isAdmin(): bool
    {
        return $this->name === self::ADMIN;
    }

    public function isEqual(self $role): bool
    {
        return $this->getName() === $role->getName();
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName($name):void
    {
        $this->name=$name;
    }

}

app/src/Controller/Users/RoleController.php
<?php
declare(strict_types=1);

namespace App\Controller\Users;

use App\Model\User\Entity\User\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Model\User\UseCase\Role;
use App\ReadModel\User\UserFetcher;
use App\Controller\ErrorHandler;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
/**
 * Class UsersController
 * @package App\Controller
 * @Route("/user/role")
 * @IsGranted ("ROLE_MANAGE_USERS")
 */
class RoleController extends AbstractController
{
    private ErrorHandler $errors;

    public function __construct(ErrorHandler $errors)
    {
        $this->errors = $errors;
    }

    /**
     * @Route ("/{id}", name="users.role")
     * @param User $user
     * @param Request $request
     * @param Role\Handler $handler
     * @return Response
     */
    public function role(User $user,Request $request,Role\Handler $handler):Response
    {
        if ($user->getId()->getValue() === $this->getUser()->getId()) {
            $this->addFlash('error', 'Unable to change role for yourself.');
            return $this->redirectToRoute('users.show', ['id' => $user->getId()]);
        }

        $command= Role\Command::fromUser($user);
        $form=$this->createForm(Role\Form::class,$command);

        if($form->isSubmitted() && $form->isValid()){
            try{
                $handler->handle($command);
                return $this->redirectToRoute('users.show',['id'=>$user->getId()]);
            }catch (\DomainException $e){
                $this->errors->warning($e->getMessage(),['exception'=>$e]);
                $this->addFlash('error',$e->getMessage());
            }
        }
        return $this->render('app/users/role.html.twig',[
            'user'=>$user,
            'form'=>$form->createView()
        ]);
    }
}

app/src/Controller/Users/StatusController.php
<?php
declare(strict_types=1);

namespace App\Controller\Users;

use App\Model\User\Entity\User\User;
use App\Model\User\UseCase\Activate;
use App\Model\User\UseCase\Block;
use App\Controller\ErrorHandler;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
/**
 * @Route("/users/status", name="users.status")
 * @IsGranted ("ROLE_MANAGE_USERS")
 */
class StatusController extends AbstractController
{
    private $errors;

    public function __construct(ErrorHandler $errors)
    {
        $this->errors = $errors;
    }

    /**
     * @Route("/{id}/activate", name=".activate", methods={"POST"})
     * @param User $user
     * @param Request $request
     * @param Activate\Handler $handler
     * @return Response
     */
    public function activate(User $user,Request $request, Activate\Handler $handler):Response
    {
        if (!$this->isCsrfTokenValid('activate', $request->request->get('token'))) {
            return $this->redirectToRoute('users.show', ['id' => $user->getId()]);
        }
        $command = new Activate\Command($user->getId()->getValue());

        try {
            $handler->handle($command);
        }catch (\DomainException $e) {
            $this->errors->handle($e);
            $this->addFlash('error', $e->getMessage());
        }
        return $this->redirectToRoute('users.show',['id'=>$user->getId()]);
    }

    /**
     * @Route("/{id}/block", name=".block", methods={"POST"})
     * @param User $user
     * @param Request $request
     * @param Block\Handler $handler
     * @return Response
     */
    public function block(User $user,Request $request,Block\Handler $handler):Response
    {
        if (!$this->isCsrfTokenValid('block', $request->request->get('token'))) {
            return $this->redirectToRoute('users.show', ['id' => $user->getId()]);
        }

        if ($user->getId()->getValue() === $this->getUser()->getId()) {
            $this->addFlash('error', 'Unable to block yourself.');
            return $this->redirectToRoute('users.show', ['id' => $user->getId()]);
        }

        $command= new Block\Command($user->getId()->getValue());

        try{
            $handler->handle($command);
        }catch(\DomainException $e){
            $this->errors->warning($e->getMessage(),['exception'=>$e]);
            $this->addFlash('error',$e->getMessage());
        }
        return $this->redirectToRoute('users.show', ['id' => $user->getId()]);
    }
}

app/src/Controller/Users/UsersController.php
<?php
declare(strict_types=1);

namespace App\Controller\Users;

use App\Model\User\Entity\User\User;
use App\ReadModel\User\Filter;
use App\ReadModel\User\UserFetcher;
use App\ReadModel\Work\Members\Member\MemberFetcher;
use App\Controller\ErrorHandler;
use App\Model\User\UseCase\Edit;
use App\Model\User\UseCase\Create;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Model\User\UseCase\SignUp\Confirm;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * Class UsersController
 * @package App\Controller
 * @Route("/users", name="users")
 */
class UsersController extends AbstractController
{
    private const PER_PAGE=50;
    private ErrorHandler $errors;

    public function __construct(ErrorHandler $errors)
    {
        $this->errors = $errors;
    }

    /**
     * @Route("/",name="")
     * return Response
     */
    public function index(Request $request,UserFetcher $fetcher):Response
    {
        $filter = new Filter\Filter();
        $form = $this->createForm(Filter\Form::class, $filter);
        $form->handleRequest($request);
        $users=$fetcher->all(
            $filter,
            $request->query->getInt('page', 1),
            self::PER_PAGE,
            $request->query->get('sort', 'created_at'),
            $request->query->get('direction', 'desc')
        );
        return $this->render('app/users/index.html.twig',
            [
                'users' => $users,
                'form' => $form->createView()
            ]);
    }

    /**
     * @Route("/create", name=".create")
     * @param Request $request
     * @param Create\Handler $handler
     * @return Response
     * @IsGranted("ROLE_MANAGE_USERS")
     */
    public function create(Request $request, Create\Handler $handler): Response
    {
        $command = new Create\Command();

        $form = $this->createForm(Create\Form::class, $command);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $handler->handle($command);
                return $this->redirectToRoute('users');
            } catch (\DomainException $e) {
                $this->errors->handle($e);
                $this->addFlash('error', $e->getMessage());
            }
        }

        return $this->render('app/users/create.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/edit", name=".edit")
     * @param User $user
     * @param Request $request
     * @param Edit\Handler $handler
     * @return Response
     * @IsGranted("ROLE_MANAGE_USERS")
     */
    public function edit(User $user, Request $request, Edit\Handler $handler): Response
    {
        $command = Edit\Command::fromUser($user);

        $form = $this->createForm(Edit\Form::class, $command);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $handler->handle($command);
                return $this->redirectToRoute('users.show', ['id' => $user->getId()]);
            } catch (\DomainException $e) {
                $this->errors->handle($e);
                $this->addFlash('error', $e->getMessage());
            }
        }

        return $this->render('app/users/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name=".show")
     * @param User $user
     * @return Response
     * @IsGranted("ROLE_MANAGE_USERS")
     */
    public function show(User $user, MemberFetcher $members): Response
    {
        $member = $members->find($user->getId()->getValue());
        return $this->render('app/users/show.html.twig', compact('user','member'));
    }

    /**
     * @Route("/{id}/confirm", name=".confirm", methods={"POST"})
     * @param User $user
     * @param Request $request
     * @param Confirm\Manual\Handler $handler
     * @return Response
     * @IsGranted("ROLE_MANAGE_USERS")
     */
    public function confirm(User $user, Request $request, Confirm\Manual\Handler $handler): Response
    {
        if (!$this->isCsrfTokenValid('confirm', $request->request->get('token'))) {
            return $this->redirectToRoute('users.show', ['id' => $user->getId()]);
        }

        $command = new Confirm\Manual\Command($user->getId()->getValue());

        try {
            $handler->handle($command);
        } catch (\DomainException $e) {
            $this->errors->handle($e);
            $this->addFlash('error', $e->getMessage());
        }

        return $this->redirectToRoute('users.show', ['id' => $user->getId()]);
    }
}

app/templates/app/users/create.html.twig
{% extends 'base.html.twig' %}


{% block title %}Users{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{{ path('users') }}">Users</a></li>
    <li class="breadcrumb-item active">Create</li>
{% endblock %}

{% block body %}

    <div class="card">
        <div class="card-body">

            {{ form_start(form) }}
            {{ form_widget(form) }}
            <button type="submit" class="btn btn-primary">Create</button>
            {{ form_end(form) }}

        </div>
    </div>

{% endblock %}

app/templates/app/users/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Users{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{{ path('users') }}">Users</a></li>
    <li class="breadcrumb-item"><a href="{{ path('users.show', {'id': user.id}) }}">{{ user.name.full }}</a></li>
    <li class="breadcrumb-item active">Edit</li>
{% endblock %}

{% block body %}

    <div class="card">
        <div class="card-body">

            {{ form_start(form) }}
            {{ form_widget(form) }}
            <button type="submit" class="btn btn-primary">Save</button>
            {{ form_end(form) }}

        </div>
    </div>

{% endblock %}

app/templates/app/users/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Users{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item active">Users</li>
{% endblock %}

{% block body %}
    <div class="card">
        <div class="card-header">
            <i class="fa fa-align-justify"></i> Users
        </div>

        <div class="card-body">

            <div class="controls">
                <a href="{{ path('users.create') }}" class="btn btn-success">Create User</a>
                <a href="{{ path('users') }}" class="btn btn-outline-secondary">Reset Search</a>
            </div>

            {{ form_start(form) }}
                <table class="table table-responsive-sm table-bordered">
                    <thead>
                        <tr>
                            <th>{{ knp_pagination_sortable(users, 'Date', 'created_at') }}</th>
                            <th>{{ knp_pagination_sortable(users, 'Name', 'name') }}</th>
                            <th>{{ knp_pagination_sortable(users, 'Email', 'email') }}</th>
                            <th>{{ knp_pagination_sortable(users, 'Role', 'role') }}</th>
                            <th>{{ knp_pagination_sortable(users, 'Status', 'status') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td></td>
                        <td>{{ form_widget(form.name) }}</td>
                        <td>{{ form_widget(form.email) }}</td>
                        <td>{{ form_widget(form.role) }}</td>
                        <td>{{ form_widget(form.status) }}</td>
                    </tr>
                    {% for user in users %}
                        <tr>
                            <td>{{ user.created_at|date('Y-m-d') }}</td>
                            <td><a href="{{ path('users.show', {'id': user.id}) }}">{{ user.name }}</a></td>
                            <td>{{ user.email }}</td>
                            <td>{{ user_role(user.role) }}</td>
                            <td>{{ user_status(user.status) }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {{ form_end(form) }}
        </div>
    </div>
    <div class="navigation">
        {{ knp_pagination_render(users) }}
    </div>
{% endblock %}

app/templates/app/users/role.html.twig
{% extends 'base.html.twig' %}

{% block title %}User role{% endblock %}

{% block breadcrumbs %}
        <li class="breadcrumb-item"><a href="{{ path('users') }}">Users</a></li>
        <li class="breadcrumb-item"><a href="{{ path('users.show', {'id': user.id}) }}">{{ user.name.full }}</a></li>
        <li class="breadcrumb-item active">Role</li>
{% endblock %}

{% block body %}

    <div class="card">
        <div class="card-body">

            {{ form_start(form) }}
            {{ form_widget(form) }}
            <button type="submit" class="btn btn-primary">Save</button>
            {{ form_end(form) }}

        </div>
    </div>

{% endblock %}

app/templates/app/users/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Users{% endblock %}

{% block breadcrumbs %}
        <li class="breadcrumb-item active">{{ user.name.full }}</li>
{% endblock %}

{% block body %}
    <div class="card">
        <div class="card-header"><i class="fa fa-align-justify"></i> Simple Table</div>
        <div class="card-body">
            <div class="controls">

                {% if user.id.value != app.user.id %}
                    <a href="{{ path('users.edit', {'id': user.id}) }}" class="btn btn-primary">Edit</a>
                    <a href="{{ path('users.role', {'id': user.id}) }}" class="btn btn-primary">Change Role</a>
                {% endif %}
                {% if user.wait %}
                    <form action="{{ path('users.confirm', {'id': user.id}) }}" method="post" onsubmit="return confirm('Are you sure?')">
                        <input type="hidden" name="token" value="{{ csrf_token('confirm') }}" />
                        <button type="submit" class="btn btn-success">Confirm</button>
                    </form>
                {% endif %}
                {% if user.active and user.id.value != app.user.id %}
                    <form action="{{ path('users.status.block', {'id': user.id}) }}" method="post" onsubmit="return confirm('Are you sure?')">
                        <input type="hidden" name="token" value="{{ csrf_token('block') }}" />
                        <button type="submit" class="btn btn-danger">Block</button>
                    </form>
                {% endif %}
                {% if user.blocked %}
                    <form action="{{ path('users.status.activate', {'id': user.id}) }}" method="post" onsubmit="return confirm('Are you sure?')">
                        <input type="hidden" name="token" value="{{ csrf_token('activate') }}" />
                        <button type="submit" class="btn btn-success">Activate</button>
                    </form>
                {% endif %}
                {% if is_granted('ROLE_WORK_MANAGE_MEMBERS') %}
                    {% if member %}
                        <a href="{{ path('work.members.show', {'id': member.id}) }}" class="btn btn-primary">View Member</a>
                    {% else %}
                        <a href="{{ path('work.members.create', {'id': user.id}) }}" class="btn btn-primary">Create Member</a>
                    {% endif %}
                {% endif %}
            </div>
                <table class="table table-responsive-sm table-bordered">
                    <tbody>
                        <tr>
                            <th>Name</th>
                            <td>{{ user.name.full }}</td>
                        </tr>
                        <tr>
                            <th>Email</th>
                            <td>{{ user.email ? user.email.value : '' }}</td>
                        </tr>
                        <tr>
                            <th>Created</th>
                            <td>{{ user.date|date('Y-m-d H:i:s') }}</td>
                        </tr>
                        <tr>
                            <th>Role</th>
                            <td>{{ user_role(user.role.name) }}</td>
                        </tr>
                        <tr>
                            <th>Status</th>
                            <td>{{ user_status(user.status) }}</td>
                        </tr>
                    </tbody>
                </table>
        </div>
    </div>


    {% if user.networks %}
        <div class="box">
            <table class="table table-bordered mb-0">
                <tbody>
                {% for network in user.networks %}
                    <tr>
                        <th>{{ network.network }}</th>
                        <td>{{ network.identity }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}

{% endblock %}